### PR TITLE
Add network-related metrics

### PR DESCRIPTION
**Pull request by ygabuev**
This PR adds some metrics for the Network Interfaces, namely:
- health of network interfaces
- health of network ports
- link status (Up or Down) of network ports
- speed of network ports

Those can easily be extended since there is quite a lot of fields and parameters exported by iDRAC.

### CODE REVIEW

**Comment by mrlhansen** [comment]
Thank you for the contribution!

Before I merge it, please make the following two changes, to better follow standard practices for naming metrics.

1. Rename `idrac_network_port_link_status` to `idrac_network_port_link_up` with a value of `1` for up state and a value of `0` for down state.
2. Rename `idrac_network_port_speed` to `idrac_network_port_speed_mbps` such that the units are clear.

**Comment by ygabuev** [comment]
@mrlhansen Done, thanks for feedback. Could you also take a look at [this other](https://github.com/mrlhansen/idrac_exporter/pull/43) PR of mine?

**Comment by mrlhansen** [comment]
Yes, I will merge all of it now, but I probably won't have time to make a new release until the weekend.

**Comment by ygabuev** [comment]
Thank you!

**Pull request merged**
